name: trip_repository
description: The Repo that handles trips
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

    
  place_repository:
    path: ../place_repository  
  # equatable: ^2.0.5
  cloud_firestore: ^5.6.4
  firebase_auth: ^5.5.0
  firebase_storage: ^12.4.3
  path: ^1.8.3
  dio: ^5.4.3+1
  flutter_config: ^2.0.2
  # rxdart: ^0.27.7
  # path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true